### ISSUE TITLE
FFMPEG Configuration

### ISSUE THREAD

**Issue by MrBond-85** [SupImDos/homebridge-camera-swann#4]
### **Describe Your Problem:**
I am trying to configure my Swann NVR within HomeBridge however each of the cameras returns an error. It appears FFMPEG is exiting with error code -4058 but i cant find any reference to what this might be anywhere.
I have confirmed the stream works via VLC without an issue. I have also installed FFMPEG in the C: drive as per the install instructions.

I have tried excluding the username (HomeBridge) and password (HomeKit) from the url but it returns the same result indicating it is not an authentication issue.

 Any ideas?

### **Logs:**
```
[12/12/2020, 2:00:56 pm] [Camera-Swann] Homekit requested: 299Kbps. Starting main stream from: Front Door
ffmpeg -re -i rtsp://HomeBridge:HomeKit@192.168.1.5:554/ch01/0 -map 0:0 -vcodec copy -an -f rawvideo -payload_type 99 -ssrc 12788106 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params njXbWL6bTFy0C8WSJ1rhFlm/u8Vs1vACaz5MgpCj srtp://192.168.1.220:58288?rtcpport=58288&localrtcpport=58288&pkt_size=1378 -loglevel debug
[12/12/2020, 2:00:56 pm] [Camera-Swann] An error occured while making stream request
[12/12/2020, 2:00:56 pm] [Camera-Swann] Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [
    '-re',
    '-i',
    'rtsp://HomeBridge:HomeKit@192.168.1.5:554/ch01/0',
    '-map',
    '0:0',
    '-vcodec',
    'copy',
    '-an',
    '-f',
    'rawvideo',
    '-payload_type',
    '99',
    '-ssrc',
    '12788106',
    '-f',
    'rtp',
    '-srtp_out_suite',
    'AES_CM_128_HMAC_SHA1_80',
    '-srtp_out_params',
    'njXbWL6bTFy0C8WSJ1rhFlm/u8Vs1vACaz5MgpCj',
    'srtp://192.168.1.220:58288?rtcpport=58288&localrtcpport=58288&pkt_size=1378',
    '-loglevel',
    'debug'
  ]
}
[12/12/2020, 2:00:56 pm] [Camera-Swann] **ERROR: FFmpeg exited with code -4058**

```
### **Homebridge Config:**
```
{
            "cameras": [
                {
                    "name": "Front Door",
                    "manufacturer": "Swann",
                    "motion": false,
                    "videoConfig": {
                        "mainStream": "-re -i rtsp://HomeBridge:HomeKit@192.168.1.5:554/ch01/0",
                        "subStream": "-re -i rtsp://HomeBridge:HomeKit@192.168.1.5:554/ch01/1",
                        "debug": false
                    }
                }
            ],
            "platform": "Camera-Swann"
        },
```
### **json**
```
{
    "bridge": {
        "name": "Homebridge 8DA8",
        "username": "0E:55:66:A0:8D:A8",
        "port": 51000,
        "pin": "220-01-626"
    },
    "accessories": [

        _{
            "cameras": [
                {
                    "name": "Front Door",
                    "manufacturer": "Swann",
                    "motion": false,
                    "videoConfig": {
                        "mainStream": "-re -i rtsp://HomeBridge:HomeKit@192.168.1.5:554/ch01/0",
                        "subStream": "-re -i rtsp://HomeBridge:HomeKit@192.168.1.5:554/ch01/1",
                        "debug": false
                    }
                }
            ],
            "platform": "Camera-Swann"
        },_
        {
            "refreshToken": "********************",
            "onlyDeviceTypes": [
                "doorbell_v3"
            ],
            "platform": "Ring"
        }
    ]
}


```

### **Environment:**

* **Node.js Version**: 14.15.1
* **NPM Version**: 6.14.8
* **Homebridge Version**: <1.1.6>
* **Homebridge Camera FFmpeg Version**: Homebridge-camera-swann v1.0.4
* **Homebridge Config UI X Plugin Version**:homebridge-config-ui-x v4.36.0
* **Operating System**: Windows 10

**Comment by SupImDos** [comment]
It seems that Homebridge isn't finding your FFMPEG installation properly. It's possible that means it wasn't installed properly, or your PATH variable wasn't set correctly.

Unfortunately I don't run Homebridge on Windows, so it's hard for me to help.

Have you had a look and tried either of these?

https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/341

https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/299
